# Generated by Django 5.2.1 on 2025-05-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'User with this Username already exists.'}, max_length=150, unique=True),
        ),
    ]
