# Generated by Django 5.2.1 on 2025-05-17 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discussions', '0002_groupmembership_alter_discussiongroup_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(blank=True, help_text='The textual content of the message.', null=True)),
                ('file_attachment', models.FileField(blank=True, help_text='An optional file attached to the message.', null=True, upload_to='group_chat_files/%Y/%m/%d/')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The date and time when the message was created.')),
                ('group', models.ForeignKey(help_text='The discussion group this message belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='discussions.discussiongroup')),
                ('user', models.ForeignKey(help_text='The user who sent this message.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Chat Message',
                'verbose_name_plural': 'Group Chat Messages',
                'ordering': ['timestamp'],
            },
        ),
    ]
