# Generated by Django 5.2.1 on 2025-05-17 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('source_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_content_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.contentitem')),
                ('authors', models.CharField(blank=True, max_length=500)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('article_type', models.CharField(blank=True, max_length=50)),
            ],
            bases=('content.contentitem',),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.contentitem')),
                ('author', models.CharField(max_length=255)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True)),
            ],
            bases=('content.contentitem',),
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.contentitem')),
                ('version', models.CharField(blank=True, max_length=50)),
                ('format', models.CharField(blank=True, max_length=50)),
            ],
            bases=('content.contentitem',),
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.contentitem')),
                ('speaker', models.CharField(max_length=255)),
                ('event_name', models.CharField(blank=True, max_length=255)),
                ('lecture_date', models.DateField(blank=True, null=True)),
            ],
            bases=('content.contentitem',),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.contentitem')),
                ('director', models.CharField(max_length=255)),
                ('release_year', models.PositiveIntegerField()),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
            ],
            bases=('content.contentitem',),
        ),
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.contentitem')),
                ('creator', models.CharField(blank=True, max_length=255)),
                ('start_year', models.PositiveIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
            ],
            bases=('content.contentitem',),
        ),
        migrations.CreateModel(
            name='WebResource',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.contentitem')),
                ('resource_type', models.CharField(blank=True, help_text='E.g., Website, Report, Forum Thread', max_length=100)),
            ],
            bases=('content.contentitem',),
        ),
    ]
