# Generated by Django 5.2.1 on 2025-05-17 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', help_text='The role of the user in this group.', max_length=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_details', to='discussions.discussiongroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_group_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Membership',
                'verbose_name_plural': 'Group Memberships',
                'ordering': ['date_joined'],
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.RemoveField(
            model_name='discussiongroup',
            name='members',
        ),
        migrations.AddField(
            model_name='discussiongroup',
            name='members',
            field=models.ManyToManyField(
                blank=True, 
                related_name='discussion_groups_joined', 
                through='discussions.GroupMembership', 
                through_fields=('group', 'user'), 
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
