# Generated by Django 5.2.1 on 2025-05-18 03:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('discussions', '0002_groupmembership_alter_discussiongroup_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='discussiongroup',
            constraint=models.UniqueConstraint(fields=('creator', 'name'), name='unique_group_name_per_creator'),
        ),
    ]
